# name: form_inputs
# version: 1.0.0+1
# publish_to: none

# environment:
#   sdk: '^3.1.0-163.1.beta'

# dependencies: 
#   formz: ^0.4.1


name: form_inputs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  formz: ^0.4.1

dev_dependencies:
  very_good_analysis: ^2.4.0